### ISSUE TITLE
Wipe does not play to end in 2.1.3 works in 2.1.RC2

### ISSUE THREAD

**Issue by olzzon** [nrkno/sofie-casparcg-server#17]
Playing Wipe.mov (using Wipe.mov from installation) does not play the last frame on CCG 2.1.3 whereas on CCG 2.1.RC2 it plays correctly.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/29782499/51664196-2ca60780-1fb9-11e9-92ad-d51b42bf9207.png">

**Comment by Julusian** [comment]
This could be the same issue as https://github.com/nrkno/tv-automation-casparcg-server/issues/3? 
I shall try and test this out soon

**Comment by Julusian** [comment]
This should be long fixed, and will not be a problem in the 2.4 builds
