### ISSUE TITLE
LOADBG AUTO doesn't start play using some files

### ISSUE THREAD

**Issue by lapoguidi** [nrkno/sofie-casparcg-server#19]
Hi,
I really love your fork of CasparCG Server, because it merge the good work of the original CasparCG but with some usefull functions form video playout.

How to reproduce the problem I get: (using the console)
`PLAY 1-1 AMB`
the video AMB starts play, then i write
`LOADBG 1-1 GO1080P25 AUTO`
and the video GO1080P25 starts as soon as the AMB video ended, then i write
`LOADBG 1-1 AMB AUTO`
but the AMB video will never play

I tried manually writing it directly from the console, or sending with a "client".
Using the SCHEDULE SET command, at scheduled timecode the command is running, but the result is the same.

With latest official CasparCG this works fine.
I'm doing something wrong?

Thank you

**Comment by jesperstarkar** [comment]
Which 2.1.nrk.x version are you using? Have you tried our latest release?

**Comment by lapoguidi** [comment]
Hi jesperstakar,
I discovered that problem yesterday with v2.1.4_NRK, so I updated to v2.1.6_NRK with the same results.

Thanks

**Comment by sirfnomi** [comment]
try with different file instead of GO1080P25

**Comment by lapoguidi** [comment]
Hi irfnomi,
I tried with all the files in media folder and also with mp4 I rendered.
Also I tried with same spec files (all 1080p25 or 720p25 or 1080i50...) and mixing them up, but with the same result.
As additional test, I tried sending LOADBG command asap after the PLAY command, after some seconds and near the end.

A strange issue:
`PLAY 1-1 AMB`
`LOADBG 1-1 AMB AUTO`
the auto play works fine and still works also if I resend `LOADBG 1-1 AMB AUTO` again

Thanks

**Comment by sirfnomi** [comment]
i'm facing another type of issue related to this
when i play with seek or IN command and send loadbg auto then foreground file destroyed with in 2 seconds

> PLAY 1-1 ClipA SEEK 100
> LOADBG 1-1 ClipB AUTO

after sending loadbg ClipB starts before ending of ClipA

**Comment by Julusian** [comment]
@sirfnomi Which version are you getting that with? I remember that we did some tweaks to how seek works in 2.1.7 so it would be good to know if this behaviour changed in that version.

**Comment by sirfnomi** [comment]
i found this issue in 2.1.6, 2.1.7 and 2.1.8 not sure about previous releases.

**Comment by lapoguidi** [comment]
I tested today v2.1.8 and I can confirm, as @sirfnomi said, that the issue still there.
Analyzing OSC infos, using a C++ server and also [casparcg-state-scanner by olzzon](https://github.com/olzzon/casparcg-state-scanner) I saw that "time" of last played frame is not sharp: I try to explain better, if a clip has a duration of 10.0 seconds, the last time received from OSC is 9.720000267028809.
I don't know if this can focus the issue or if this is an unuseful information, but this is what I saw.
At this moment I'm not able to fix or have found a workaround.

**Comment by TondaKrist** [comment]
Still same problem in lastest build :( LOADBG with AUTO option is not starting a next clip in some videos.

**Comment by sirfnomi** [comment]
today i was testing on interlaced mode (PAL) with Server 2.1.11 and i found 2 different things that server is not playing next file with loadbg

Case 1:
with [this media file](https://drive.google.com/file/d/1hoovxpw5hgEfZQSHkNB3ZUlhZOHdoNXw/view?usp=sharing)  server is playing this file completely but it is not playing next file loaded with Loadbg command.

Case 2:
and according to OSC information with [this another media file](https://drive.google.com/file/d/1EUxhaBBrwfiojSzYSWxgjhMEKo6Sw9J9/view?usp=sharing) server end this file 6 frames later and maybe that's why next file with loadbg is not playing.

Server 2.1 Beta 2 playing both files without any issue

**Comment by hreinnbeck** [comment]
I just tested these files from @sirfnomi.  Auto works in 1080 p/i 50 but not in PAL.  @TondaKrist - are you running in PAL?

**Comment by TondaKrist** [comment]
Hi, this occurs in 1080 p/i too. Please see file attached. Seems that video track will never reach its end according to OSC an info. [download here](https://bit.ly/2TkXsPN)

**Comment by Phil403** [comment]
I came across the same issue when using version 2.1.12
As stated before some files are playing until the very end, like the "AMB" File, some like "GO1080P25" are not playing to the last frame  and not triggering a LOADBG.
This is also shown in the DIAG window.

![image](https://user-images.githubusercontent.com/24254497/105752024-16840680-5f47-11eb-902d-ee88d98a10d1.png)

![image](https://user-images.githubusercontent.com/24254497/105752134-30bde480-5f47-11eb-9910-a1af791c82a7.png)

If a file like GO1080P25 ends playing, sending a "PLAY 1-1" plays the next file.

This also appears on other files rendered via Premiere (XDCAM MXF)
Doing the same with original 2.1 beta 2 works fine.

I am using a Decklink output and format 1080i50

**Comment by Julusian** [comment]
This does not sound applicable to the new 2.4 builds
