### ISSUE TITLE
Multichannel Performance

### ISSUE THREAD

**Issue by Phil403** [nrkno/sofie-casparcg-server#20]
I am trying different configurations on HP and Supermicro platforms with 1 CPU and 2 CPUs. I am getting a lot of performance warnings when going above 3 channels of 1080i50.
For example my 2CPU build with a Decklink Quad 2 and 2x Xeon 6128 runs 6ch at 20-25% CPU and  6-10% GPU (Quadro P2000), but still gets warnings.
Are there any recommendations regarding hardware? I remember that there was a performance discussion at the SVT build as well with a similar issue, going above 3 channels.

**Comment by Julusian** [comment]
There arent really any documented recommendations. The main one is that dual cpu machines are not at all tested and I suspect they will cause weird issues due to the arrangement of pcie lanes.
Both xeons and i7/i9 cpus should work fine with multiple channels, with recent quadro or geforce cards

**Comment by Sidonai-1** [comment]
When you use dual socket machines you have to tune the settings a lot more: I found that disabling Numa nodes (and even Hyperthreading sometimes) was the only way that Caspar would run multiple channels correctly.
