### ISSUE TITLE
VERSION FLASH - odd response

### ISSUE THREAD

**Issue by sparkpunkd** [nrkno/sofie-casparcg-server#24]
The AMCP command `VERSION FLASH` does not produce a version number as documented. 

```
VERSION FLASH
201 VERSION OK
$(build.FlashMajorVersion).$(build.FlashMinorVersion).$(build.FlashBuildVersion).$(build.FlashPrivateVersion)
```

**Comment by Julusian** [comment]
CasparCG is pulling that version number straight from the windows registry. Windows 10 is shipping with flash player, and is not putting a correct value in the registry on all machines (it was correct on only 2 of 4 machines I tested), so this isn't something under our control.
