### ISSUE TITLE
CG INFO - generally not helpful

### ISSUE THREAD

**Issue by sparkpunkd** [nrkno/sofie-casparcg-server#25]
For template host info (e.g. `CG 1-2 INFO`) and specific layer info (e.g. `CG 1-2 INFO 10`), most template types provide either an empty string of fixed value string. 

This is with the exception of flash templates that attempt to provide information. However, the following snippet is the result of a template host info query:

```
CG 1-2 ADD 10 PHONE 1
202 CG OK
CG 1-2 INFO
201 CG OK
<string>&lt;TemplateHostInfo version=&quot;2.0.4.3803 RC&quot; width=&quot;1920&quot; height=&quot;1080&quot; fps=&quot;25&quot; totalMemory=&quot;8298496&quot; freeMemory=&quot;2404352&quot; loadedTemplates=&quot;1&quot;&gt;\n  &lt;Layers&gt;\n    &lt;layer id=&quot;10&quot; visibleTemplate=&quot;Template older than 2.0&quot;/&gt;\n  &lt;/Layers&gt;\n&lt;/TemplateHostInfo&gt;</string>
```

For information on a specific layer:
```
CG 1-2 INFO 10
201 CG OK
<string>This function is asynchronous. The result is returned by the external call function OnTemplateDescription</string>
```

**Comment by Julusian** [comment]
I suspect something in newer versions of windows or flash has broken this and #24, as nothing has changed in this code in years. Not really sure how much it is worth fixing though, as I think 2.2+ removes these commands completely
