### ISSUE TITLE
Routed HTML Layer animation is not smooth

### ISSUE THREAD

**Issue by sirfnomi** [nrkno/sofie-casparcg-server#27]
**Description**
routed html animation is not smooth when routing an individual layer from another channel.
Animation is feeling like fields order are different.

> CG 2-1 ADD 1 "HTMLfile" 1
> PLAY 1-1 route://2-1

But when we route whole channel animation is smooth

> PLAY 1-1 route://2

Both channel is on same video mode PAL

**Expected Behaviour**

Routed html animation should be smooth as it is playing on own channel.

**Steps To Reproduce**
> CG 2-1 ADD 1 "HTMLTemp" 1
> play 1-1 route://2-1

**Environment**
Server : 2.1.8
Windows: 7

One more thing routing an empty layer again and again is not uninitialized already routed layer

> play 1-1 route://2-1
> play 1-1 route://2-1
> play 1-1 route://2-1
> play 1-1 route://2-1

And when we stop 1-1 then all 4 layer producers uninitialized.

**Comment by sirfnomi** [comment]
After testing I found that in progressive mode routed layer is smooth and in interlaced mode routing a routed layer is same as routed layer ( not smooth )

**Comment by sirfnomi** [comment]
hi,
Is there any hope for a solution to this issue in the near future?

**Comment by nytamin** [comment]
This is not a feature that we're currently using at NRK, so we probably won't be fixing it ourselves any time soon.

We would be happy to accept a Pull Request though!

**Comment by sirfnomi** [comment]
Ok Thanks 👍

**Comment by Julusian** [comment]
This does not sound applicable to the new 2.4 builds
