### ISSUE TITLE
HTML enable GPU problem

### ISSUE THREAD

**Issue by bencius** [nrkno/sofie-casparcg-server#35]
Hello, I'm having a problem, when i change HTML enable gpu to true. My HTML template starts to render with jitters and after some time it starts to go fluent. What for is this option? Because templates play in worse way than without it. I have 1050 TI from nVidia. Thanks for any help.

**Comment by Julusian** [comment]
What version are you using?
In all of the released versions, the enable-gpu option has some performance problems which is why it is disabled by default. It should perform a lot better in a build of current master, as that has full gpu acceleration support for html templates.

**Comment by bencius** [comment]
@Julusian for now I'm using latest version.

**Comment by Julusian** [comment]
If this is still a problem, could you retry with v2.1.11?

**Comment by sirfnomi** [comment]
with or without enable GPU i m noticing a little lag/stutter only when we start server and load html template and after that it is smooth perfectly.

but with GPU Enable getting multiple exception error when stopping cg layer with stop 1-1 or loading html again on same cg layer without stopping html template with cg 1-1 stop 1.

on this state i think cg producer is not properly destroying and it crashed also server is not shutting down then properly with 'q' command.

**Comment by bencius** [comment]
> If this is still a problem, could you retry with v2.1.11?

Same problem...

**Comment by bencius** [comment]
Yes, confirming problem still exists....

**Comment by Julusian** [comment]
The html producer code has had a lot of work done to ensure smoothness since the last comment. At NRK we are happy with how it behaves in 2.4NRK with gpu-enabled in 1080i50 channels on various GPUs.
So hopefully this is better for everyone now
