### ISSUE TITLE
Not playing any transition in 2.10

### ISSUE THREAD

**Issue by Sega01** [nrkno/sofie-casparcg-server#42]
Hi, 

I'm using the 2.10 version of the server with the 2.0.8 client. 
Now I have the follwing problem: when I want to start a video with a transition (for example: mix) it just starts it with a cut. 
I tried to do the same in the 2.4 version and there the video starts perfectly with the transition. 
Any ideas why thats so?

**Comment by dimitry-ishenko** [comment]
@Sega01 try playing empty frame before the first transition (PLAY 1-10 EMPTY). Or from the Client add a Solid Color or Fade Out transition at the beginning of your playlist.

**Comment by Julusian** [comment]
This does not sound applicable to the new 2.4 builds
