### ISSUE TITLE
50P

### ISSUE THREAD

**Issue by 5opr4ni** [nrkno/sofie-casparcg-server#5]
When playing 1080P5000 it plays with 25P speed. (half the framerate)

/olle

**Comment by jesperstarkar** [comment]
Thanks for the issue.

We have currently removed the framerate producer which disables conversion of framerates. This also breaks SD/HD conversion.

Looking into re-adding framerate producer for better cross compatibility.

**Comment by Julusian** [comment]
This should be working in the latest commit, and is awaiting a bit more testing

**Comment by 5opr4ni** [comment]
Santa brought some testfiles to me, so I will test this.

**Comment by 5opr4ni** [comment]
Don't have a build for this, have to wait for work before I can test. If you don't have somewhere where I can pick it up. :)
Happy Christmas to you all.
