### ISSUE TITLE
Unable to play HTML templates

### ISSUE THREAD

**Issue by 7u5a** [nrkno/sofie-casparcg-server#63]
### Expected behaviour
Wan't to play HTML template.

### Current behaviour
Seems that it will not find my HTML templates.
Testet with the media scanner in the package, then I can't play them, but with the media scanner from 2.3.3 LTS it is possible top lay the HTML

----

### Steps to reproduce
1. Start server
2. Start scanner
3. Start client
4. Make rundown with html template

### Environment
* Commit: [00f6c8b]
* Server version: [2.4.0 NRK-RC2]
* Operating system: [Windows 10]

---

### Screenshots
If applicable, add screenshots as complementary information.

**Comment by jstarpl** [comment]
At NRK, playing HTML templates from disk is not something we are very much invested in, so it's very unlikely that we'll look into this. I would suggest checking out the latest beta of the upstream CasparCG Server: https://github.com/CasparCG/server/releases/tag/v2.4.0-rc1 and if this is still a problem, file a bug report there.

Kind regards,
Jan
