### ISSUE TITLE
Vertical resolution loss with HDCAM 50 MXF capture

### ISSUE THREAD

**Issue by TKooijmans** [nrkno/sofie-casparcg-server#64]
### Observed Behavior

I noticed that capture image quality with 2.1 is better then with 2.4 version.
This only seems the case with HDCAM 1080i50 MXF capture. capture in MP4 format seems fine.
Vertical resolution seems reduced with 2.4 version

![Grab CasparCG 2 1 capture](https://github.com/user-attachments/assets/611c594e-bb17-4a53-bcec-84b4340e83d0)
![Grab CasparCG 2 4 capture](https://github.com/user-attachments/assets/3d1dfdd8-64df-4f72-b9e4-a356364cec5f)
![1080_Test](https://github.com/user-attachments/assets/f9dabdd8-1a6b-4bb4-864e-76e56a74f720)

### Expected behaviour

The same capture quality as with CasparCG 2.1

### Steps to reproduce

1.Setup with CasperCG 2.1
 SET 1 MODE 1080i5000
 PLAY 1-1 Decklink 1 FORMAT 1080i5000 CHANNEL_LAYOUT stereo
 record file with
ADD 1 FILE "Testclip HD.mxf" -b 50000000 -acodec pcm_s24le -vcodec mpeg2video -pix_fmt yuv422p -alternate_scan 1 -g 12 -bf 2 -minrate 50000k -maxrate 50000k -color_primaries bt709 -color_trc 1 -colorspace 1 -dc 10 -lmin 1*QP2LAMBDA

Setup with CasperCG 2.4
 SET 1 MODE 1080i5000
 PLAY 1-1 Decklink 1 FORMAT 1080i5000
record file with
ADD 1-700 FILE "TEST 2.4 NRK.mxf" -b:v 50000000 -codec:a pcm_s24le -codec:v mpeg2video -filter:v interlace,zscale=rangein=full:range=limited:primaries=709:transfer=709:matrix=709,format=yuv422p -alternate_scan:v 1 -g:v 12 -bf:v 2 -minrate:v 50000k -maxrate:v 50000k -color_primaries:v bt709 -color_trc:v 1 -colorspace:v 1 -filter:a pan=stereo|c0=c0|c1=c1

2 feed a HD SDI 1080i50 (TV broadcast) to the SDI input of the Decklink card, use the CasparCG test picture
2.Capture from a Decklink HD SDI source in HDCAM 50 mode with CasparCG 2.1 and Caspar 2.4

3. compare the image quality between CasparCG 2.1 capture and CasparCG2.4 capture
   vertical resolution has decreased with CasparCG 2.4 capture

### Environment

Server 2.1 and 2.4
Win 10 Pro with Decklink Extreme4k and Nvidia graphics

**Comment by nytamin** [comment]
Hi! Thank you for the bug report!
I see that you've reported this [upstream as well](https://github.com/CasparCG/server/issues/1574), I don't think that we'll be prioritizing looking into this issue for the NRK fork, so I'll close this one.
