### ISSUE TITLE
Building CCG on Ubuntu 18.04LTS

### ISSUE THREAD

**Issue by olzzon** [nrkno/sofie-casparcg-server#7]
When I try to build CasparCG on Ubuntu I get this error:
```
[ 52%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_resource_manager.cc.o
[ 53%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_scoped_temp_dir.cc.o
[ 53%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_stream_resource_handler.cc.o
[ 53%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_xml_object.cc.o
[ 53%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/cef_zip_archive.cc.o
[ 54%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/libcef_dll_wrapper.cc.o
[ 54%] Building CXX object modules/html/libcef_dll_wrapper/CMakeFiles/libcef_dll_wrapper.dir/wrapper/libcef_dll_wrapper2.cc.o
[ 54%] Linking CXX static library libcef_dll_wrapper.a
[ 54%] Built target libcef_dll_wrapper
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
Command exited with non-zero status 2
Build time 0:38.03
make failed
```

I´m not sure if that´s the same issue they have here: https://github.com/CasparCG/server/issues/1003

I´ve build the libcef_dll_wrapper.a : (based on what happens in the dockerfile and in the "extract-deps-from-docker" file.
```
download and extract: http://opensource.spotify.com/cefbuilds/cef_binary_3.3239.1723.g071d1c1_linux64_minimal.tar.bz2
cd cef_binary*/build
cmake ./..
make -j8
```
I have the libcef_dll_wrapper.a file created, but don´t know where to copy it, og what else I should do.
Does anyone have a hint :)

**Comment by olzzon** [comment]
Thanks a lot for the tip i’ll try and fix that :)

**Comment by ThommiTechnik** [comment]
HeyHo :) Am I'm doing something wrong, or is the bug not fixed? Getting the same error, also in FFMOEG, with the latest build/source-code under Ubuntu 18.04.2 LTS.

Thanks, and Cheers, Thomas

**Comment by Julusian** [comment]
@ThommiTechnik No, building on linux has not been worked on any further

**Comment by ThommiTechnik** [comment]
> @ThommiTechnik No, building on linux has not been worked on any further

OK, Thanks for info 👍

**Comment by swordh** [comment]
Are there any plans on a linux build? I really want the batch command that is available in NRK version, but I also want to run CasparCG in linux.

**Comment by nchasovnikov** [comment]
> Thanks a lot for the tip i’ll try and fix that :)

Have you managed to build it successfully?

**Comment by olzzon** [comment]
No, I ended up spending my time on other stuff, and just run CasparCG on windows

**Comment by dimitry-ishenko** [comment]
@olzzon I know the year is about to turn to 2021 :smiley: but here you go:

https://casparcgforum.org/t/casparcg-server-2-1-12-nrk-for-ubuntu-20-04-and-18-04/3787
